# Prometheus global configuration
global:
  scrape_interval: 15s  # How often to scrape metrics from targets
  evaluation_interval: 15s  # How often to evaluate alert rules  

# Define scrape configurations for metric collection
scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'  # Job identifier
    static_configs:
      - targets: ['localhost:9090']  # Prometheus API endpoint
  - job_name: 'loki'  # Job identifier for Loki
    static_configs:
      - targets: ['loki:3100']  # Loki API endpoint for metrics
  - job_name: 'tempo'  # Job identifier for Tempo
    static_configs:
      - targets: ['tempo:3200']  # Tempo API endpoint for metrics    
  - job_name: 'grafana'  # Job identifier for Grafana
    static_configs:
      - targets: ['grafana:3000']  # Grafana API endpoint for metrics
  - job_name: 'otel-collector'  # Job identifier for the collector
    static_configs:
      - targets: ['otel-collector:8889']  # Prometheus metrics exporter endpoint for OpenTelemetry Collector
  - job_name: 'otel-collector-internal'  # Job identifier for the collector internal metrics
    static_configs:
      - targets: ['otel-collector:8888']  # Internal metrics endpoint for OpenTelemetry Collector